//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelOrderTestEntities2 : DbContext
    {
        public HotelOrderTestEntities2()
            : base("name=HotelOrderTestEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RoomMember> RoomMember { get; set; }
        public virtual DbSet<Comments> 回饋評價 { get; set; }
        public virtual DbSet<房型資訊管理> 房型資訊管理 { get; set; }
    }
}
