//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public string RoomID { get; set; }
        public string RoomClassID { get; set; }
        public Nullable<int> RoomSize { get; set; }
        public Nullable<int> RoomPeople { get; set; }
        public string RoomStyleID { get; set; }
        public Nullable<int> HotelID { get; set; }
        public string RoomStatus { get; set; }
        public string AdminID { get; set; }
    }
}
