//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class 房型資訊管理
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 房型資訊管理()
        {
            this.回饋評價 = new HashSet<Comments>();
        }
    
        public string RoomID { get; set; }
        public string RoomClassificationID { get; set; }
        public int PingNumber { get; set; }
        public int NumberPeople { get; set; }
        public string RoomStyleID { get; set; }
        public int HotelID { get; set; }
        public string RoomStatus { get; set; }
        public string AdminID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> 回饋評價 { get; set; }
    }
}
